#!/usr/bin/env python3
"""Generates cmd/teploy-arcade/frontend/favicon.svg.

An isometric arcade cabinet in Tron-style neon, drawn natively on a 16x16 grid.

Three things make it work at tab size, each learned by getting it wrong first:

  * Three solid planes, not outlines. An outlined cabinet reads as stacked
    stripes when shrunk; solid mass survives. The front, the receding side and
    the lit top are each a filled shape.
  * Grey carries the planes; neon is only trim. Colouring the whole body made
    it read as a pink box rather than a dark cabinet lit by neon. The three
    greys do the 3D work, and the magenta and cyan sit on the edges.
  * The top face is not optional. Dropping it - which an early neon version did
    - collapses the icon into a front panel with a bar beside it. It is the
    single pixel row that makes the thing three-dimensional.

Everything sits on whole pixels and renders with crispEdges, so it stays a
pixel grid at any size instead of anti-aliasing into a smudge.

Edit the map, then run:  python3 tools/favicon.py
"""
import os

PAL = {
    '.': None,          # transparent - the rounded tile shows through
    # Greys carry the mass and the three planes. The cabinet is a dark object
    # *lit* by neon, not an object made of neon - colouring the whole body
    # turned it into a pink box.
    'P': '#33333d',     # front face
    'K': '#1e1e26',     # side face, in shadow
    'U': '#4a4a58',     # top face, catching light
    'u': '#2a2a34',     # top face where it turns onto the side
    'D': '#101015',     # bezel and control panel
    # Neon appears only as trim.
    'M': '#f43ff0',     # magenta - marquee and the lit front edge
    'm': '#7a1f78',     # magenta falloff - the floor glow
    'C': '#3fe4ff',     # cyan - the side's lit edge
    'c': '#1d6b80',     # cyan falloff
    'S': '#2b6be0',     # screen
    'W': '#9fd8ff',     # screen glint
}

CABINET = [
    "................",
    "...........ccc..",
    "..UUUUUUUUUuuu..",
    "..MPPPPPPPPKKC..",
    "..MMMMMMMMMKKC..",
    "..MPSSSSSWPKKC..",
    "..MPSSSSSSPKKC..",
    "..MPSSSSSSPKKC..",
    "..MPPPPPPPPKKC..",
    "..MPDDPPDDPKKC..",
    "..MPPPPPPPPKKC..",
    "..MMMMMMMMMKKC..",
    "..MPPPPPPPPKKC..",
    "..MPPPPPPPPKKC..",
    "..MP.....PPKKC..",
    "...mmmmmmm..c...",
]

TILE_BG = "#08080e"  # near black, so the neon actually reads as neon


def render(rows, bg=TILE_BG, radius=3):
    n = len(rows)
    rects = []
    for y, row in enumerate(rows):
        x = 0
        while x < len(row):
            c = row[x]
            if PAL.get(c) is None:
                x += 1
                continue
            run = 1
            while x + run < len(row) and row[x + run] == c:
                run += 1
            rects.append(f'<rect x="{x}" y="{y}" width="{run}" height="1" fill="{PAL[c]}"/>')
            x += run
    return (
        "<!-- Generated by tools/favicon.py - edit the pixel map there, not this file. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {n} {n}" shape-rendering="crispEdges">\n'
        f'  <rect width="{n}" height="{n}" rx="{radius}" fill="{bg}"/>\n  '
        + "\n  ".join(rects)
        + "\n</svg>\n"
    )


if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "cmd", "teploy-arcade", "frontend", "favicon.svg")
    with open(out, "w") as f:
        f.write(render(CABINET))
    print("wrote", out)
